version: '3.8'
services:
  master:
    #Cribl image to pull down
    image: cribl/cribl:latest
    #ENV Vars to pass on container creation
    environment:
      - CRIBL_DIST_MODE=master
      #Create a token for bootstraping your workers below
      - CRIBL_DIST_LEADER_URL=tcp://<Insert_your_token_here>@0.0.0.0:4200
      - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
    ports:
    #First port is the host second is the container so adjust as needed
      - "9000:9000"
    #You will want to add additional for sources and destinations they will not need to mapped to the host
    volumes:
      #Working dir on host this will keep the cluster persitent
      - "~/cribl-config:/opt/cribl/config-volume"
  workers:
    image: cribl/cribl:latest
    #This is telling Docker to wait for the creation of the leader/master container
    depends_on:
      - master
    environment:
      - CRIBL_DIST_MODE=worker
      # Put your master token created above in the below space
      - CRIBL_DIST_LEADER_URL=tcp://<Insert_above_token_here>@master:4200
    ports:
      - 9000
